name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/arm/v7
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/task-manager:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USERNAME }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          docker pull ghcr.io/${{ github.repository_owner }}/task-manager:latest
          docker stop task-manager || true
          docker rm task-manager || true
          docker run -d --name task-manager \
            -p 3000:5000 \
            -v /home/${{ secrets.PI_USERNAME }}/task-manager/data:/app/data \
            --restart unless-stopped \
            ghcr.io/${{ github.repository_owner }}/task-manager:latest