version: '3'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: task-manager-backend
    ports:
      - "5000:5000"
    volumes:
      - ../data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=5000
    restart: unless-stopped
    networks:
      - task-manager-network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: task-manager-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - PORT=3001
    restart: unless-stopped
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge