version: '3'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: task-manager-backend
    ports:
      - "5000:5000"
    volumes:
      - ../data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    restart: unless-stopped
    networks:
      - task-manager-network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: task-manager-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - PORT=3001
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - task-manager-network

  # Nginx reverse proxy for SSL termination (uncomment when deploying with SSL)
  # nginx:
  #   image: nginx:alpine
  #   container_name: task-manager-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/ssl:/etc/nginx/ssl
  #   depends_on:
  #     - frontend
  #     - backend
  #   restart: unless-stopped
  #   networks:
  #     - task-manager-network

networks:
  task-manager-network:
    driver: bridge